name: Deploy Sagemaker Domain

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCRESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ENVIROMENT: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        user: actions/checkout@v4

      - name: Set Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Set AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          aws --version
          /usr/local/bin/aws --version

      - name: Set credentials
        run: |
          /usr/local/bin/aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          /usr/local/bin/aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          /usr/local/bin/aws configure set default.region ${{ secrets.AWS_REGION }}
          export AWS_REGION=${{ secrets.AWS_REGION }}
          echo $AWS_REGION

      - name: Deploy domain
        run: bash deploy.sh $ENVIRONMENT